export const data = {
	filters: {
		season: "2022",
		group: "GROUP_A",
	},
	resultSet: {
		count: 6,
		first: "2022-11-20",
		last: "2022-11-29",
		played: 0,
	},
	competition: {
		id: 2000,
		name: "FIFA World Cup",
		code: "WC",
		type: "CUP",
		emblem: "https://crests.football-data.org/qatar.png",
	},
	matches: [
		{
			area: {
				id: 2267,
				name: "World",
				code: "INT",
				flag: null,
			},
			competition: {
				id: 2000,
				name: "FIFA World Cup",
				code: "WC",
				type: "CUP",
				emblem: "https://crests.football-data.org/qatar.png",
			},
			season: {
				id: 1382,
				startDate: "2022-11-21",
				endDate: "2022-12-18",
				currentMatchday: 1,
				winner: null,
			},
			id: 391882,
			utcDate: "2022-11-20T16:00:00Z",
			status: "TIMED",
			matchday: 1,
			stage: "GROUP_STAGE",
			group: "GROUP_A",
			lastUpdated: "2022-08-12T13:10:39Z",
			homeTeam: {
				id: 8030,
				name: "Qatar",
				shortName: "Qatar",
				tla: "QAT",
				crest: "https://crests.football-data.org/8030.svg",
			},
			awayTeam: {
				id: 791,
				name: "Ecuador",
				shortName: "Ecuador",
				tla: "ECU",
				crest: "https://crests.football-data.org/791.svg",
			},
			score: {
				winner: null,
				duration: "REGULAR",
				fullTime: {
					home: null,
					away: null,
				},
				halfTime: {
					home: null,
					away: null,
				},
			},
			odds: {
				msg: "Activate Odds-Package in User-Panel to retrieve odds.",
			},
			referees: [],
		},
		{
			area: {
				id: 2267,
				name: "World",
				code: "INT",
				flag: null,
			},
			competition: {
				id: 2000,
				name: "FIFA World Cup",
				code: "WC",
				type: "CUP",
				emblem: "https://crests.football-data.org/qatar.png",
			},
			season: {
				id: 1382,
				startDate: "2022-11-21",
				endDate: "2022-12-18",
				currentMatchday: 1,
				winner: null,
			},
			id: 391881,
			utcDate: "2022-11-21T16:00:00Z",
			status: "TIMED",
			matchday: 1,
			stage: "GROUP_STAGE",
			group: "GROUP_A",
			lastUpdated: "2022-08-12T13:10:39Z",
			homeTeam: {
				id: 804,
				name: "Senegal",
				shortName: "Senegal",
				tla: "SEN",
				crest: "https://crests.football-data.org/senegal.svg",
			},
			awayTeam: {
				id: 8601,
				name: "Netherlands",
				shortName: "Netherlands",
				tla: "NED",
				crest: "https://crests.football-data.org/8601.svg",
			},
			score: {
				winner: null,
				duration: "REGULAR",
				fullTime: {
					home: null,
					away: null,
				},
				halfTime: {
					home: null,
					away: null,
				},
			},
			odds: {
				msg: "Activate Odds-Package in User-Panel to retrieve odds.",
			},
			referees: [],
		},
		{
			area: {
				id: 2267,
				name: "World",
				code: "INT",
				flag: null,
			},
			competition: {
				id: 2000,
				name: "FIFA World Cup",
				code: "WC",
				type: "CUP",
				emblem: "https://crests.football-data.org/qatar.png",
			},
			season: {
				id: 1382,
				startDate: "2022-11-21",
				endDate: "2022-12-18",
				currentMatchday: 1,
				winner: null,
			},
			id: 391883,
			utcDate: "2022-11-25T13:00:00Z",
			status: "TIMED",
			matchday: 2,
			stage: "GROUP_STAGE",
			group: "GROUP_A",
			lastUpdated: "2022-08-12T13:10:39Z",
			homeTeam: {
				id: 8030,
				name: "Qatar",
				shortName: "Qatar",
				tla: "QAT",
				crest: "https://crests.football-data.org/8030.svg",
			},
			awayTeam: {
				id: 804,
				name: "Senegal",
				shortName: "Senegal",
				tla: "SEN",
				crest: "https://crests.football-data.org/senegal.svg",
			},
			score: {
				winner: null,
				duration: "REGULAR",
				fullTime: {
					home: null,
					away: null,
				},
				halfTime: {
					home: null,
					away: null,
				},
			},
			odds: {
				msg: "Activate Odds-Package in User-Panel to retrieve odds.",
			},
			referees: [],
		},
		{
			area: {
				id: 2267,
				name: "World",
				code: "INT",
				flag: null,
			},
			competition: {
				id: 2000,
				name: "FIFA World Cup",
				code: "WC",
				type: "CUP",
				emblem: "https://crests.football-data.org/qatar.png",
			},
			season: {
				id: 1382,
				startDate: "2022-11-21",
				endDate: "2022-12-18",
				currentMatchday: 1,
				winner: null,
			},
			id: 391884,
			utcDate: "2022-11-25T16:00:00Z",
			status: "TIMED",
			matchday: 2,
			stage: "GROUP_STAGE",
			group: "GROUP_A",
			lastUpdated: "2022-08-12T13:10:39Z",
			homeTeam: {
				id: 8601,
				name: "Netherlands",
				shortName: "Netherlands",
				tla: "NED",
				crest: "https://crests.football-data.org/8601.svg",
			},
			awayTeam: {
				id: 791,
				name: "Ecuador",
				shortName: "Ecuador",
				tla: "ECU",
				crest: "https://crests.football-data.org/791.svg",
			},
			score: {
				winner: null,
				duration: "REGULAR",
				fullTime: {
					home: null,
					away: null,
				},
				halfTime: {
					home: null,
					away: null,
				},
			},
			odds: {
				msg: "Activate Odds-Package in User-Panel to retrieve odds.",
			},
			referees: [],
		},
		{
			area: {
				id: 2267,
				name: "World",
				code: "INT",
				flag: null,
			},
			competition: {
				id: 2000,
				name: "FIFA World Cup",
				code: "WC",
				type: "CUP",
				emblem: "https://crests.football-data.org/qatar.png",
			},
			season: {
				id: 1382,
				startDate: "2022-11-21",
				endDate: "2022-12-18",
				currentMatchday: 1,
				winner: null,
			},
			id: 391885,
			utcDate: "2022-11-29T15:00:00Z",
			status: "TIMED",
			matchday: 3,
			stage: "GROUP_STAGE",
			group: "GROUP_A",
			lastUpdated: "2022-08-12T13:10:39Z",
			homeTeam: {
				id: 8601,
				name: "Netherlands",
				shortName: "Netherlands",
				tla: "NED",
				crest: "https://crests.football-data.org/8601.svg",
			},
			awayTeam: {
				id: 8030,
				name: "Qatar",
				shortName: "Qatar",
				tla: "QAT",
				crest: "https://crests.football-data.org/8030.svg",
			},
			score: {
				winner: null,
				duration: "REGULAR",
				fullTime: {
					home: null,
					away: null,
				},
				halfTime: {
					home: null,
					away: null,
				},
			},
			odds: {
				msg: "Activate Odds-Package in User-Panel to retrieve odds.",
			},
			referees: [],
		},
		{
			area: {
				id: 2267,
				name: "World",
				code: "INT",
				flag: null,
			},
			competition: {
				id: 2000,
				name: "FIFA World Cup",
				code: "WC",
				type: "CUP",
				emblem: "https://crests.football-data.org/qatar.png",
			},
			season: {
				id: 1382,
				startDate: "2022-11-21",
				endDate: "2022-12-18",
				currentMatchday: 1,
				winner: null,
			},
			id: 391886,
			utcDate: "2022-11-29T15:00:00Z",
			status: "TIMED",
			matchday: 3,
			stage: "GROUP_STAGE",
			group: "GROUP_A",
			lastUpdated: "2022-08-12T13:10:39Z",
			homeTeam: {
				id: 791,
				name: "Ecuador",
				shortName: "Ecuador",
				tla: "ECU",
				crest: "https://crests.football-data.org/791.svg",
			},
			awayTeam: {
				id: 804,
				name: "Senegal",
				shortName: "Senegal",
				tla: "SEN",
				crest: "https://crests.football-data.org/senegal.svg",
			},
			score: {
				winner: null,
				duration: "REGULAR",
				fullTime: {
					home: null,
					away: null,
				},
				halfTime: {
					home: null,
					away: null,
				},
			},
			odds: {
				msg: "Activate Odds-Package in User-Panel to retrieve odds.",
			},
			referees: [],
		},
	],
};
